[theme]
primaryColor="#00aaff"          # Blue accent for interactive elements
backgroundColor="#1a1a1a"       # Dark gray background
secondaryBackgroundColor="#2a2a2a"  # Slightly lighter gray for contrast
textColor="#e0e0e0"             # Light gray text for readability
font="sans serif"               # Default sans-serif; customized via CSS